routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

/**************RESPUESTA DE PASARELA DE PAGO************/
Route::post('pago/confirm', 'ListaPlanController@confirm')->name('pago.confirm');
Route::get('pago/confirmget', 'ListaPlanController@confirm')->name('pago.confirmget');

Route::group(['middleware' => ['auth']], function() { //**************************PERFILES*******////
    Route::get('perfil/cliente', 'PerfilController@cliente')->name('perfil.cliente');
    Route::post('perfil/cliente', 'PerfilController@clienteUpdate')->name('perfil.clienteUpdate');
    Route::get('perfil/recolector', 'PerfilController@recolector')->name('perfil.recolector');

    /**************RESPUESTA DE PASARELA DE PAGO************/
    Route::post('pago/response', 'ListaPlanController@response')->name('pago.response');

});

Route::get('/app', function () {
  return redirect('app/index');
});

/**************Control del FrontEnd**************/
Route::group(['middleware' => ['web']], function () {

  Route::prefix('app')->group(function (){

    Route::get('/', 'FrontendController@index')->name('frontend.index');
    Route::get('/login', 'FrontendController@loginForm')->name('frontend.loginForm');
    Route::get('/logout', 'FrontendController@logout')->name('frontend.logout');
    Route::post('/login/authenticate', 'FrontendController@authenticate')->name('frontend.authenticate');
    Route::get('/registro', 'FrontendController@registroForm')->name('frontend.registroForm');
    Route::post('/registro/signup', 'FrontendController@signup')->name('frontend.signup');
    Route::get('/home', 'FrontendController@home')->name('frontend.home');

    Route::get('/account', 'FrontendController@account')->name('frontend.account')->middleware('auth.frontend');
    Route::post('/account/update', 'FrontendController@updateAccount')->name('frontend.account.update')->middleware('auth.frontend');
    Route::get('/mensual', 'FrontendController@mensual')->name('frontend.mensual');
    Route::get('/pago', 'FrontendController@pago')->name('frontend.pago');
    Route::get('/planes', 'FrontendController@planes')->name('frontend.planes');
    Route::get('/planes/{planId}', 'FrontendController@plan')->name('frontend.plan');
    Route::get('/tarjeta', 'FrontendController@tarjeta')->name('frontend.tarjeta');
    Route::get('/trimestral', 'FrontendController@trimestral')->name('frontend.trimestral');
  });

});

/**************OBTENER DIAS HABILITADOS PARA RECOLECCCION**************/
Route::get('/getAvailableDays', 'AjaxController@getAvailableDays')->name('ajax.getAvailableDays');

Route::group(['middleware' => ['auth', 'CheckClientePerfil']], function() { /**************El cliente debe tener el perfil completado para ingresar a estas opciones****/

    /*Route::get('/', function () {
        return view('welcome');
    });*/

    Route::get('/home', 'HomeController@index')->name('home');
    Route::get('/', 'HomeController@index')->name('home');

	/*****************CLIENTES***********************/
	Route::get('cliente/{cliente}/setStatus', 'ClienteController@setStatus')->name('cliente.setStatus');
	Route::get('cliente/{cliente}/destroy', 'ClienteController@destroy')->name('cliente.destroy');
	Route::post('cliente/{cliente}/update', 'ClienteController@update')->name('cliente.update');
    Route::resource('cliente', ClienteController::class, [
    	'except' => [ 'destroy','update']
    ]);

    /*****************RECOLECTORES***********************/
	Route::get('recolector/{recolector}/setStatus', 'RecolectorController@setStatus')->name('recolector.setStatus');
	Route::get('recolector/{recolector}/destroy', 'RecolectorController@destroy')->name('recolector.destroy');
	Route::post('recolector/{recolector}/update', 'RecolectorController@update')->name('recolector.update');
    Route::resource('recolector', RecolectorController::class, [
    	'except' => [ 'destroy','update']
    ]);

    /*****************PLANES***********************/
    Route::get('plan/{plan}/setStatus', 'PlanController@setStatus')->name('plan.setStatus');
    Route::get('plan/{plan}/destroy', 'PlanController@destroy')->name('plan.destroy');
    Route::post('plan/{plan}/update', 'PlanController@update')->name('plan.update');
    Route::resource('plan', PlanController::class, [
        'except' => [ 'destroy','update']
    ]);

    /*****************ZONAS***********************/
    Route::get('zona/{zona}/setStatus', 'ZonaController@setStatus')->name('zona.setStatus');
    Route::get('zona/{zona}/destroy', 'ZonaController@destroy')->name('zona.destroy');
    Route::post('zona/{zona}/update', 'ZonaController@update')->name('zona.update');
    Route::resource('zona', ZonaController::class, [
        'except' => [ 'destroy','update']
    ]);

    /*****************RUTAS***********************/
    Route::get('ruta/{ruta}/setStatus', 'RutaController@setStatus')->name('ruta.setStatus');
    Route::get('ruta/{ruta}/destroy', 'RutaController@destroy')->name('ruta.destroy');
    Route::post('ruta/{ruta}/update', 'RutaController@update')->name('ruta.update');
    Route::get('ruta/index/{daySelected?}/{weekSelected?}', 'RutaController@index')->name('ruta.index');
    Route::resource('ruta', RutaController::class, [
        'except' => [ 'destroy','update', 'index']
    ]);

    /*****************REASIGNAR FECHAS ***********************/
    Route::get('reasignar/{fecha?}', 'HomeController@reasignarFechas')->name('reasignar');

    /*****************RECOLECTOR RUTA***********************/
    Route::get('rutarecolector', 'RecolectorRutaController@index')->name('ruta.recolector');

    /*****************RECOLECTOR REPORTE***********************/
    Route::get('reporterecolector', 'ReporteRecolectorController@index')->name('reporte.recolector');
    Route::get('reportegeneral', 'ReporteGeneralController@index')->name('reporte.general');


    /*****************PAGOS RECOLECTORES***********************/
    Route::get('pagosrecolector', 'PagosRecolectorController@index')->name('pagos.recolector');
    Route::get('saveHistory', 'PagosRecolectorController@saveHistory')->name('pagos.saveHistory');
    Route::get('historial', 'PagosRecolectorController@historial')->name('pagos.historial');

    /***********************PETICIONES AJAX***************/
    Route::post('/updateRecolectorRoute','AjaxController@updateRecolectorRoute')->name('ajax.updateRecolectorRoute');
    Route::post('/updateNovedadRoute','AjaxController@updateNovedadRoute')->name('ajax.updateNovedadRoute');
    Route::post('/updateForEventDay','AjaxController@updateForEventDay')->name('ajax.updateForEventDay');
    Route::post('/saveRecolectionStatus','AjaxController@saveRecolectionStatus')->name('ajax.saveRecolectionStatus');
    Route::post('/setNewDateEvent','AjaxController@setNewDateEvent')->name('ajax.setNewDateEvent');
    Route::post('/updateDateEvent','AjaxController@updateDateEvent')->name('ajax.updateDateEvent');
    Route::post('/deleteDateEvent','AjaxController@deleteDateEvent')->name('ajax.deleteDateEvent');
    Route::post('/validatePickup','AjaxController@validatePickup')->name('ajax.validatePickup');
    Route::post('/deleteImage','AjaxController@deleteImage')->name('ajax.deleteImage');

    /***********************Lista de planes para clientes***************/
    Route::get('listado/planes','ListaPlanController@index')->name('listado.planes');

    /***********************Historico de pagos Cliente***************/
    Route::get('historial/cliente','PerfilController@historialPayments')->name('historial.cliente');

    /***********************Historico de pagos ADMIN***************/
    Route::get('historial/clientes','PerfilController@historialPaymentsAdmin')->name('historial.clientes');

    /******************ZONAS y RUTAS CONFIG********************/
    Route::get('mapa/index', 'MapaController@index')->name('mapa.index');
    Route::resource('mapa', MapaController::class, [
        'except' => [ 'destroy','update']
    ]);

    /******************Inventarios********************/
    Route::get('inventarios/index', 'InventariosController@index')->name('inventarios.index');
    Route::get('inventarios/{inventarios}/destroy', 'InventariosController@destroy')->name('inventarios.destroy');
    Route::post('inventarios/{item}/update', 'InventariosController@update')->name('inventarios.update');
    Route::resource('inventarios', InventariosController::class, [
        'except' => [ 'destroy','update']
    ]);

    /******************LISTADO DE RUTAS********************/
    /*Route::get('listarutas/index', 'ListaRutasController@index')->name('listarutas.index');
    Route::resource('listarutas', ListaRutasController::class, [
        'except' => [ 'destroy','update']
    ]);*/

});

app/Recolector.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Recolector extends Model
{
	protected $table = 'users';

    protected $fillable = [
        'name', 'email', 'password', 'image',
    ];
}

app/Http/Controllers/RecolectorController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Config;
use App\Recolector;

class RecolectorController extends Controller
{
    protected $customMessages = [
            'required' => 'El campo :attribute es obligatorio.',
            'email' => 'El campo :attribute debe ser un Email valido.',
            'regex' => 'El campo :attribute debe contener solo letras.',
            'unique' => 'El Email indicado ya se encuentra registrado en la base de datos.',
            'confirmed' => 'El password debe coincidir con la confirmación del password.',
            'numeric' => 'El campo :attribute debe ser numerico.',
            'image' => 'La foto debe ser de un formato valido (jpeg, png, bmp, gif, svg, or webp).'
        ];

    protected $niceNames = [
            'name' => 'Nombre Completo',
            'email' => 'Email',
            'color' => 'Color del Vehiculo',
            'placa' => 'Placa del Vehiculo',
            'vehiculo' => 'Vehiculo del Vehiculo',
        ];

    public function index()
    {
        $recolectores = recolector::where('status', '<>', 2)->where('id_rol', 2)->get();
        return view('recolector/index' , ['recolectores' => $recolectores]);
    }

    public function create()
    {
        $semana = Config::get('weekDays.week');
        return view('recolector/create', ['semana' => $semana]);
    }

    public function store(Request $request)
    {
        $rules = [
            'name' => 'required|regex:/^[a-zA-ZÑñ\s]+$/',
            'placa' => 'required',
            'color' => 'required|regex:/^[a-zA-ZÑñ\s]+$/',
            'vehiculo' => 'required',
            'email' => 'required|email|unique:users,email',
            'password' => 'required|confirmed',
            'telefono' => 'required|numeric',
            'whatsapp' => 'required|numeric',
            'capacidad' => 'required|numeric',
            'image' => 'mimes:jpeg,bmp,png,jpg',
            'image-licencia' => 'mimes:jpeg,bmp,png,jpg',
            'image-soat' => 'mimes:jpeg,bmp,png,jpg'
        ];

        $this->validate($request, $rules, $this->customMessages, $this->niceNames);

        $recolector = new Recolector;
        $recolector->name = $request->input('name');
        $recolector->email = $request->input('email');
        $recolector->password = Hash::make($request->input('password'));
        $recolector->telefono = $request->input('telefono');
        $recolector->whatsapp = $request->input('whatsapp');
        $recolector->direccion = $request->input('direccion');
        $recolector->color = $request->input('color');
        $recolector->placa = $request->input('placa');
        $recolector->vehiculo = $request->input('vehiculo');
        $recolector->capacidad = $request->input('capacidad');
        $recolector->id_rol = 2;

        if($request->hasfile('image')) {
            $file = $request->file('image');
            $extension = $file->getClientOriginalExtension();
            $filename = time().'.'.$extension;
            $file->move('uploads/usuarios', $filename);
            $recolector->image = $filename;
        }
        if($request->hasfile('image-licencia')) {
            $file = $request->file('image');
            $extension = $file->getClientOriginalExtension();
            $filename = time().'-licencia.'.$extension;
            $file->move('uploads/usuarios', $filename);
            $recolector->licencia = $filename;
        }
        if($request->hasfile('image-soat')) {
            $file = $request->file('image');
            $extension = $file->getClientOriginalExtension();
            $filename = time().'-soat.'.$extension;
            $file->move('uploads/usuarios', $filename);
            $recolector->soat = $filename;
        }

        else {
            $recolector->image = 'no-photo.png';
        }

        $semana = Config::get('weekDays.week');
        $daysSelected = $request->input('dia_recoleccion');
        $daysJson = array();
        foreach($semana as $key => $dia) {
          if(in_array($key, $daysSelected)){
            $daysJson[$key] = 1;
          }else{
            $daysJson[$key] = 0;
          }
        }
        $recolector->dias_recoleccion = json_encode($daysJson);

        $recolector->save();

        return redirect('recolector')->with('success','Registro guardado con éxito.');
    }

    public function show($id)
    {
        //
    }

    public function edit($id)
    {
        $recolector = Recolector::findOrFail($id);
        $semana = Config::get('weekDays.week');
        $diasRecoleccion = json_decode($recolector->dias_recoleccion, true);

        return view('recolector/edit',[
                                        'recolector' => $recolector,
                                        'semana' => $semana,
                                        'diasRecoleccion' => $diasRecoleccion
                                       ]);
    }

    public function update(Request $request, $id)
    {
        $recolector = Recolector::findOrFail($id);

        $rules = [
            'name' => 'required|regex:/^[a-zA-ZÑñ\s]+$/',
            'email' => 'required|email',
            'placa' => 'required',
            'color' => 'required|regex:/^[a-zA-ZÑñ\s]+$/',
            'vehiculo' => 'required',
            'telefono' => 'required|numeric',
            'capacidad' => 'required|numeric',
            'whatsapp' => 'required|numeric',
            'image' => 'mimes:jpeg,bmp,png,jpg',
            'image-licencia' => 'mimes:jpeg,bmp,png,jpg',
            'image-soat' => 'mimes:jpeg,bmp,png,jpg'

        ];

        $this->validate($request, $rules, $this->customMessages, $this->niceNames);

        $recolector->name = $request->input('name');
        $recolector->telefono = $request->input('telefono');
        $recolector->whatsapp = $request->input('whatsapp');
        $recolector->direccion = $request->input('direccion');
        $recolector->color = $request->input('color');
        $recolector->placa = $request->input('placa');
        $recolector->vehiculo = $request->input('vehiculo');
        $recolector->capacidad = $request->input('capacidad');

        if($request->hasfile('image')) {
            $file = $request->file('image');
            $extension = $file->getClientOriginalExtension();
            $filename = time().'.'.$extension;
            $file->move('uploads/usuarios', $filename);
            $recolector->image = $filename;
        }

        if($request->hasfile('image-licencia')) {
            $file = $request->file('image-licencia');
            $extension = $file->getClientOriginalExtension();
            $filename = time().'-licencia.'.$extension;
            $file->move('uploads/usuarios', $filename);
            $recolector->licencia = $filename;
        }
        if($request->hasfile('image-soat')) {
            $file = $request->file('image-soat');
            $extension = $file->getClientOriginalExtension();
            $filename = time().'-soat.'.$extension;
            $file->move('uploads/usuarios', $filename);
            $recolector->soat = $filename;
        }

        $semana = Config::get('weekDays.week');
        $daysSelected = $request->input('dia_recoleccion');
        $daysJson = array();
        foreach($semana as $key => $dia) {
          if(in_array($key, $daysSelected)){
            $daysJson[$key] = 1;
          }else{
            $daysJson[$key] = 0;
          }
        }
        $recolector->dias_recoleccion = json_encode($daysJson);
        $recolector->save();
        return redirect('recolector')->with('success','Registro editado con éxito.');
    }

    public function destroy($id)
    {
        $recolector = Recolector::findOrFail($id);
        $recolector->status = 2;
        $recolector->save();
        return redirect('recolector')->with('success','Registro eliminado con éxito.');
    }

    public function setStatus($id)
    {
        $recolector = Recolector::findOrFail($id);
        $recolector->status = $recolector->status==1?0:1;
        $recolector->save();
        return redirect('recolector')->with('success','Estado modificado con éxito.');
    }

    public function messages()
    {
        return [
            'required' => 'ES UN title is required'
        ];
    }
}

resources/views/recolector/index.blade.php
@extends('layouts.main')

@section('extras-css')
    <!-- DataTables -->
    <link rel="stylesheet" href="{{ asset('AdminLTE-3.0.2/AdminLTE-3.0.2/plugins/datatables-bs4/css/dataTables.bootstrap4.css') }}">
@endsection

@section('content')
<!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>{{ __('Administrador de Recolectores') }}</h1>
          </div>
          <div class="col-sm-6">
            <!--ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item"><a href="#">Layout</a></li>
              <li class="breadcrumb-item active">Fixed Layout</li>
            </ol-->
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">

      <div class="container-fluid">
        <div class="row">
          <div class="col-12">

          	@if ($message = Session::get('success'))
			<div class="alert alert-success alert-block">
				<button type="button" class="close" data-dismiss="alert">×</button>
			        <strong>{{ $message }}</strong>
			</div>
			@endif

            <!-- Default box -->
            <a href="{{ route('recolector.create') }}" class="btn btn-primary">Agregar Recolector</a>
            <br><br>
            <div class="card card-primary">
              <div class="card-header">
                <h3 class="card-title">{{ __('Listado de Recolectores') }}</h3>

                <div class="card-tools">
                  <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
                    <i class="fas fa-minus"></i></button>
                  <button type="button" class="btn btn-tool" data-card-widget="remove" data-toggle="tooltip" title="Remove">
                    <i class="fas fa-times"></i></button>
                </div>
              </div>
              <div class="card-body">

	              <table id="example1" class="table table-bordered table-striped">
	                <thead>
	                <tr>
	                  <th>Nombre</th>
	                  <th>Email</th>
	                  <th>Estado</th>
	                  <th>Acciones</th>
	                </tr>
	                </thead>
	                <tbody>
	                @foreach ($recolectores as $recolector)
	                <tr>
	                  <td>{{ $recolector->name }} <br> <img style="max-width:20px;" src="{{ asset('uploads/usuarios/'.$recolector->image) }}"></td>
	                  <td>{{ $recolector->email }}</td>
	                  <td>{{ $recolector->status==1 ? 'Activo':'Oculto' }}</td>
	                  <td>
	                  	<div class="btn-group">
						  <a href="{{ route('pagos.recolector', ['recolector' => $recolector->id]) }}">
	                        	<button type="button" class="btn btn-default" title="Pagos"><i class="fas fa-money-bill-alt"></i></button>
	                        </a>
	                  		<a href="{{ route('recolector.edit', ['recolector' => $recolector->id]) }}">
	                        	<button type="button" class="btn btn-default" title="Editar"><i class="nav-icon fas fa-edit"></i></button>
	                        </a>
	                        <a href="{{ route('recolector.setStatus', ['recolector' => $recolector->id]) }}">
	                        	<button type="button" class="btn btn-default" title="{{ $recolector->status==1 ? 'Ocultar':'Activar' }}"><i class="nav-icon fas fa-{{ $recolector->status==1 ? 'ban':'check-circle' }}"></i></button>
	                        </a>
	                        <a href="{{ route('recolector.destroy', ['recolector' => $recolector->id]) }}" onclick="return confirm('¿Estas seguro de querer eliminar este registro?. Se perderan todos los datos relacionados al mismo.')">
	                        	<button type="button" class="btn btn-default" title="Eliminar"><i class="nav-icon fas fa-trash-alt"></i></button>
	                        </a>
	                      </div>
	                  </td>
	                </tr>
	                @endforeach
	                </tbody>
	                <tfoot>
	                <tr>
	                  <th>Nombre</th>
	                  <th>Email</th>
	                  <th>Estado</th>
	                  <th>Acciones</th>
	                </tr>
	                </tfoot>
	            </table>


              </div>
              <!-- /.card-body -->
            </div>
            <!-- /.card -->
          </div>
        </div>
      </div>
    </section>
    <!-- /.content -->
@endsection

@section('extras-js')
    <!-- DataTables -->
    <script src="{{ asset('AdminLTE-3.0.2/AdminLTE-3.0.2/plugins/datatables/jquery.dataTables.js') }}"></script>
    <script src="{{ asset('AdminLTE-3.0.2/AdminLTE-3.0.2/plugins/datatables-bs4/js/dataTables.bootstrap4.js') }}"></script>

    <script>
	  $(function () {
	    $("#example1").DataTable({
        "language": {
          "url": "//cdn.datatables.net/plug-ins/1.10.15/i18n/Spanish.json"
        }
      });
	    $('#example2').DataTable({
	      "paging": true,
	      "lengthChange": false,
	      "searching": false,
	      "ordering": true,
	      "info": true,
	      "autoWidth": false,
	    });
	  });
	</script>
@endsection