routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

/**************RESPUESTA DE PASARELA DE PAGO************/
Route::post('pago/confirm', 'ListaPlanController@confirm')->name('pago.confirm');
Route::get('pago/confirmget', 'ListaPlanController@confirm')->name('pago.confirmget');

Route::group(['middleware' => ['auth']], function() { //**************************PERFILES*******////
    Route::get('perfil/cliente', 'PerfilController@cliente')->name('perfil.cliente');
    Route::post('perfil/cliente', 'PerfilController@clienteUpdate')->name('perfil.clienteUpdate');
    Route::get('perfil/recolector', 'PerfilController@recolector')->name('perfil.recolector');

    /**************RESPUESTA DE PASARELA DE PAGO************/
    Route::post('pago/response', 'ListaPlanController@response')->name('pago.response');

});

Route::get('/app', function () {
  return redirect('app/index');
});

/**************Control del FrontEnd**************/
Route::group(['middleware' => ['web']], function () {

  Route::prefix('app')->group(function (){

    Route::get('/', 'FrontendController@index')->name('frontend.index');
    Route::get('/login', 'FrontendController@loginForm')->name('frontend.loginForm');
    Route::get('/logout', 'FrontendController@logout')->name('frontend.logout');
    Route::post('/login/authenticate', 'FrontendController@authenticate')->name('frontend.authenticate');
    Route::get('/registro', 'FrontendController@registroForm')->name('frontend.registroForm');
    Route::post('/registro/signup', 'FrontendController@signup')->name('frontend.signup');
    Route::get('/home', 'FrontendController@home')->name('frontend.home');

    Route::get('/account', 'FrontendController@account')->name('frontend.account')->middleware('auth.frontend');
    Route::post('/account/update', 'FrontendController@updateAccount')->name('frontend.account.update')->middleware('auth.frontend');
    Route::get('/mensual', 'FrontendController@mensual')->name('frontend.mensual');
    Route::get('/pago', 'FrontendController@pago')->name('frontend.pago');
    Route::get('/planes', 'FrontendController@planes')->name('frontend.planes');
    Route::get('/planes/{planId}', 'FrontendController@plan')->name('frontend.plan');
    Route::get('/tarjeta', 'FrontendController@tarjeta')->name('frontend.tarjeta');
    Route::get('/trimestral', 'FrontendController@trimestral')->name('frontend.trimestral');
  });

});

/**************OBTENER DIAS HABILITADOS PARA RECOLECCCION**************/
Route::get('/getAvailableDays', 'AjaxController@getAvailableDays')->name('ajax.getAvailableDays');

Route::group(['middleware' => ['auth', 'CheckClientePerfil']], function() { /**************El cliente debe tener el perfil completado para ingresar a estas opciones****/

    /*Route::get('/', function () {
        return view('welcome');
    });*/

    Route::get('/home', 'HomeController@index')->name('home');
    Route::get('/', 'HomeController@index')->name('home');

	/*****************CLIENTES***********************/
	Route::get('cliente/{cliente}/setStatus', 'ClienteController@setStatus')->name('cliente.setStatus');
	Route::get('cliente/{cliente}/destroy', 'ClienteController@destroy')->name('cliente.destroy');
	Route::post('cliente/{cliente}/update', 'ClienteController@update')->name('cliente.update');
    Route::resource('cliente', ClienteController::class, [
    	'except' => [ 'destroy','update']
    ]);

    /*****************RECOLECTORES***********************/
	Route::get('recolector/{recolector}/setStatus', 'RecolectorController@setStatus')->name('recolector.setStatus');
	Route::get('recolector/{recolector}/destroy', 'RecolectorController@destroy')->name('recolector.destroy');
	Route::post('recolector/{recolector}/update', 'RecolectorController@update')->name('recolector.update');
    Route::resource('recolector', RecolectorController::class, [
    	'except' => [ 'destroy','update']
    ]);

    /*****************PLANES***********************/
    Route::get('plan/{plan}/setStatus', 'PlanController@setStatus')->name('plan.setStatus');
    Route::get('plan/{plan}/destroy', 'PlanController@destroy')->name('plan.destroy');
    Route::post('plan/{plan}/update', 'PlanController@update')->name('plan.update');
    Route::resource('plan', PlanController::class, [
        'except' => [ 'destroy','update']
    ]);

    /*****************ZONAS***********************/
    Route::get('zona/{zona}/setStatus', 'ZonaController@setStatus')->name('zona.setStatus');
    Route::get('zona/{zona}/destroy', 'ZonaController@destroy')->name('zona.destroy');
    Route::post('zona/{zona}/update', 'ZonaController@update')->name('zona.update');
    Route::resource('zona', ZonaController::class, [
        'except' => [ 'destroy','update']
    ]);

    /*****************RUTAS***********************/
    Route::get('ruta/{ruta}/setStatus', 'RutaController@setStatus')->name('ruta.setStatus');
    Route::get('ruta/{ruta}/destroy', 'RutaController@destroy')->name('ruta.destroy');
    Route::post('ruta/{ruta}/update', 'RutaController@update')->name('ruta.update');
    Route::get('ruta/index/{daySelected?}/{weekSelected?}', 'RutaController@index')->name('ruta.index');
    Route::resource('ruta', RutaController::class, [
        'except' => [ 'destroy','update', 'index']
    ]);

    /*****************REASIGNAR FECHAS ***********************/
    Route::get('reasignar/{fecha?}', 'HomeController@reasignarFechas')->name('reasignar');

    /*****************RECOLECTOR RUTA***********************/
    Route::get('rutarecolector', 'RecolectorRutaController@index')->name('ruta.recolector');

    /*****************RECOLECTOR REPORTE***********************/
    Route::get('reporterecolector', 'ReporteRecolectorController@index')->name('reporte.recolector');
    Route::get('reportegeneral', 'ReporteGeneralController@index')->name('reporte.general');


    /*****************PAGOS RECOLECTORES***********************/
    Route::get('pagosrecolector', 'PagosRecolectorController@index')->name('pagos.recolector');
    Route::get('saveHistory', 'PagosRecolectorController@saveHistory')->name('pagos.saveHistory');
    Route::get('historial', 'PagosRecolectorController@historial')->name('pagos.historial');

    /***********************PETICIONES AJAX***************/
    Route::post('/updateRecolectorRoute','AjaxController@updateRecolectorRoute')->name('ajax.updateRecolectorRoute');
    Route::post('/updateNovedadRoute','AjaxController@updateNovedadRoute')->name('ajax.updateNovedadRoute');
    Route::post('/updateForEventDay','AjaxController@updateForEventDay')->name('ajax.updateForEventDay');
    Route::post('/saveRecolectionStatus','AjaxController@saveRecolectionStatus')->name('ajax.saveRecolectionStatus');
    Route::post('/setNewDateEvent','AjaxController@setNewDateEvent')->name('ajax.setNewDateEvent');
    Route::post('/updateDateEvent','AjaxController@updateDateEvent')->name('ajax.updateDateEvent');
    Route::post('/deleteDateEvent','AjaxController@deleteDateEvent')->name('ajax.deleteDateEvent');
    Route::post('/validatePickup','AjaxController@validatePickup')->name('ajax.validatePickup');
    Route::post('/deleteImage','AjaxController@deleteImage')->name('ajax.deleteImage');

    /***********************Lista de planes para clientes***************/
    Route::get('listado/planes','ListaPlanController@index')->name('listado.planes');

    /***********************Historico de pagos Cliente***************/
    Route::get('historial/cliente','PerfilController@historialPayments')->name('historial.cliente');

    /***********************Historico de pagos ADMIN***************/
    Route::get('historial/clientes','PerfilController@historialPaymentsAdmin')->name('historial.clientes');

    /******************ZONAS y RUTAS CONFIG********************/
    Route::get('mapa/index', 'MapaController@index')->name('mapa.index');
    Route::resource('mapa', MapaController::class, [
        'except' => [ 'destroy','update']
    ]);

    /******************Inventarios********************/
    Route::get('inventarios/index', 'InventariosController@index')->name('inventarios.index');
    Route::get('inventarios/{inventarios}/destroy', 'InventariosController@destroy')->name('inventarios.destroy');
    Route::post('inventarios/{item}/update', 'InventariosController@update')->name('inventarios.update');
    Route::resource('inventarios', InventariosController::class, [
        'except' => [ 'destroy','update']
    ]);

    /******************LISTADO DE RUTAS********************/
    /*Route::get('listarutas/index', 'ListaRutasController@index')->name('listarutas.index');
    Route::resource('listarutas', ListaRutasController::class, [
        'except' => [ 'destroy','update']
    ]);*/

});

app/Plan.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Plan extends Model
{
    protected $table = 'plan';
    public $timestamps = false;
}

app/Http/Controllers/PlanController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use App\Plan;

class PlanController extends Controller
{
    protected $customMessages = [
            'required' => 'El campo :attribute es obligatorio.',
            'regex' => 'El campo :attribute debe contener solo letras.',
            'numeric' => 'El campo :attribute debe ser numerico.',
        ];

    protected $niceNames = [
            'titulo' => 'Titulo'
        ];

    public function index()
    {
        $plans = Plan::where('status', '<>', 2)->get();
        return view('plan/index' , ['plans' => $plans]);
    }

    public function create()
    {
        return view('plan/create');
    }

    public function store(Request $request)
    {
        $rules = [
            'titulo' => 'required',
            'descripcion' => 'required',
            'precio' => 'required|numeric',
            'frecuencia_cobro' => 'required|numeric'
        ];

        $this->validate($request, $rules, $this->customMessages, $this->niceNames);
        
        $plan = new Plan;
        $plan->titulo = $request->input('titulo');
        $plan->descripcion = $request->input('descripcion');
        $plan->precio = $request->input('precio');
        $plan->frecuencia_cobro = $request->input('frecuencia_cobro');
        $plan->recurrente = $request->has('recurrente') ? 1 : 0;
        $plan->save();

        return redirect('plan')->with('success','Registro guardado con éxito.');
    }

    public function show($id)
    {
        //
    }

    public function edit($id)
    {
        $plan = Plan::findOrFail($id);
        return view('plan/edit' , ['plan' => $plan]);
    }

    public function update(Request $request, $id)
    {
        $plan = Plan::findOrFail($id);

        $rules = [
            'titulo' => 'required',
            'descripcion' => 'required',
            'precio' => 'required|numeric',
            'frecuencia_cobro' => 'required|numeric'
        ];

        $this->validate($request, $rules, $this->customMessages, $this->niceNames);

        $plan->titulo = $request->input('titulo');
        $plan->descripcion = $request->input('descripcion');
        $plan->precio = $request->input('precio');
        $plan->frecuencia_cobro = $request->input('frecuencia_cobro');
        $plan->recurrente = $request->has('recurrente') ? 1 : 0;
        $plan->save();

        return redirect('plan')->with('success','Registro editado con éxito.');
    }

    public function destroy($id)
    {
        $plan = Plan::findOrFail($id);
        $plan->status = 2;
        $plan->save();
        return redirect('plan')->with('success','Registro eliminado con éxito.');
    }

    public function setStatus($id)
    {
        $plan = Plan::findOrFail($id);
        $plan->status = $plan->status==1?0:1;
        $plan->save();
        return redirect('plan')->with('success','Estado modificado con éxito.');
    }

    public function messages()
    {
        return [
            'required' => 'ES UN title is required'
        ];
    }
}

resources/views/plan/create.blade.php
@extends('layouts.main')

@section('content')
<!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>{{ __('Crear Plan') }}</h1>
          </div>
          <div class="col-sm-6">
            <!--ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item"><a href="#">Layout</a></li>
              <li class="breadcrumb-item active">Fixed Layout</li>
            </ol-->
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">

      <div class="container-fluid">
        <div class="row">
          <div class="col-12">

          	@if ($errors->any())
			    <div class="alert alert-danger">
			        <ul>
			            @foreach ($errors->all() as $error)
			                <li>{{ $error }}</li>
			            @endforeach
			        </ul>
			    </div>
			@endif
			
            <div class="card card-primary">
              <div class="card-header">
                <h3 class="card-title">{{ __('Datos del Plan') }}</h3>

                <div class="card-tools">
                  <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
                    <i class="fas fa-minus"></i></button>
                  <button type="button" class="btn btn-tool" data-card-widget="remove" data-toggle="tooltip" title="Remove">
                    <i class="fas fa-times"></i></button>
                </div>
              </div>
              <div class="card-body">
              
              <form method="POST" action="{{ route('plan.store') }}" enctype="multipart/form-data">
    			   @csrf
                
                <div class="row">
                	<div class="col-md-6">
                		<div class="form-group">
		                	<label>Titulo</label>
		                    <input type="text" value="{{ old('titulo') }}" class="form-control @error('titulo') is-invalid @enderror" name="titulo" id="titulo" placeholder="Titulo" required>
		                </div>

		                <div class="form-group">
		                	<label>Descripción</label>
		                    <textarea value="{{ old('descripcion') }}" class="form-control @error('descripcion') is-invalid @enderror" name="descripcion" id="descripcion" required>{{ old('descripcion') }}</textarea>
		                </div>
                	</div>

                	<div class="col-md-6">

                		<div class="form-group">
		                	<label>Frecuencia de cobro (Meses)</label>
		                    <input type="text" value="{{ old('frecuencia_cobro') }}" class="form-control @error('frecuencia_cobro') is-invalid @enderror" name="frecuencia_cobro" id="frecuenci_cobro" placeholder="Ej: 1 para un mes." required>
		                </div>

		                <div class="form-group">
		                	<label>Precio</label>
		                    <input type="text" value="{{ old('precio') }}" class="form-control @error('precio') is-invalid @enderror" name="precio" id="precio" placeholder="Precio" required>
		                </div>

		                <div class="form-group">
	                      <div class="custom-control custom-checkbox">
	                        <input class="custom-control-input" type="checkbox" id="customCheckbox1" value="recurrente" name="recurrente">
	                        <label for="customCheckbox1" class="custom-control-label">Activar Cobro recurrentes.</label>
	                      </div>
	                    </div>
		                
                	</div>

                	<div class="col-md-6">
                		<input class="btn btn-primary" type="submit" name="submit" value="Registrar">
                		<a href="{{ url()->previous() }}" class="btn btn-danger" type="button">Regresar</a>
                	</div>
                </div>

              </form>

              </div>
              <!-- /.card-body -->
            </div>
            <!-- /.card -->
          </div>
        </div>
      </div>
    </section>
    <!-- /.content -->
@endsection

resources/views/plan/edit.blade.php
@extends('layouts.main')

@section('content')
<!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>{{ __('Editar Plan') }}</h1>
          </div>
          <div class="col-sm-6">
            <!--ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item"><a href="#">Layout</a></li>
              <li class="breadcrumb-item active">Fixed Layout</li>
            </ol-->
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">

      <div class="container-fluid">
        <div class="row">
          <div class="col-12">

          	@if ($errors->any())
			    <div class="alert alert-danger">
			        <ul>
			            @foreach ($errors->all() as $error)
			                <li>{{ $error }}</li>
			            @endforeach
			        </ul>
			    </div>
			@endif
			
            <div class="card card-primary">
              <div class="card-header">
                <h3 class="card-title">{{ __('Datos del Plan') }}</h3>

                <div class="card-tools">
                  <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
                    <i class="fas fa-minus"></i></button>
                  <button type="button" class="btn btn-tool" data-card-widget="remove" data-toggle="tooltip" title="Remove">
                    <i class="fas fa-times"></i></button>
                </div>
              </div>
              <div class="card-body">
              
              <form method="POST" action="{{ route('plan.update', ['plan' => $plan->id]) }}" enctype="multipart/form-data">
    			@csrf
                
                <div class="row">
                	<div class="col-md-6">
                		<div class="form-group">
		                	<label>Titulo</label>
		                    <input type="text" value="{{ old('titulo', $plan->titulo) }}" class="form-control @error('titulo') is-invalid @enderror" name="titulo" id="titulo" placeholder="Titulo" required>
		                </div>

		                <div class="form-group">
		                	<label>Descripción</label>
		                    <textarea value="{{ old('descripcion', $plan->descripcion) }}" class="form-control @error('descripcion') is-invalid @enderror" name="descripcion" id="descripcion" required>{{ old('descripcion', $plan->descripcion) }}</textarea>
		                </div>
                	</div>

                	<div class="col-md-6">

                		<div class="form-group">
		                	<label>Frecuencia de cobro (Meses)</label>
		                    <input type="text" value="{{ old('frecuencia_cobro', $plan->frecuencia_cobro) }}" class="form-control @error('frecuencia_cobro') is-invalid @enderror" name="frecuencia_cobro" id="frecuenci_cobro" placeholder="Ej: 1 para un mes." required>
		                </div>

		                <div class="form-group">
		                	<label>Precio</label>
		                    <input type="text" value="{{ old('precio', $plan->precio) }}" class="form-control @error('precio') is-invalid @enderror" name="precio" id="precio" placeholder="Precio" required>
		                </div>

                    <div class="form-group">
                      <div class="custom-control custom-checkbox">
                        <input class="custom-control-input" type="checkbox" id="customCheckbox1" value="recurrente" name="recurrente" {{ $plan->recurrente == 1 ? 'checked':'' }}>
                        <label for="customCheckbox1" class="custom-control-label">Activar Cobro recurrentes.</label>
                      </div>
                    </div>
		                
                	</div>

                	<div class="col-md-6">
                		<input class="btn btn-primary" type="submit" name="submit" value="Registrar">
                		<a href="{{ url()->previous() }}" class="btn btn-danger" type="button">Regresar</a>
                	</div>
                </div>

              </form>

              </div>
              <!-- /.card-body -->
            </div>
            <!-- /.card -->
          </div>
        </div>
      </div>
    </section>
    <!-- /.content -->
@endsection

resources/views/plan/index.blade.php
@extends('layouts.main')

@section('extras-css')
    <!-- DataTables -->
    <link rel="stylesheet" href="{{ asset('AdminLTE-3.0.2/AdminLTE-3.0.2/plugins/datatables-bs4/css/dataTables.bootstrap4.css') }}">
@endsection

@section('content')
<!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>{{ __('Administrador de Planes') }}</h1>
          </div>
          <div class="col-sm-6">
            <!--ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item"><a href="#">Layout</a></li>
              <li class="breadcrumb-item active">Fixed Layout</li>
            </ol-->
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">

      <div class="container-fluid">
        <div class="row">
          <div class="col-12">

          	@if ($message = Session::get('success'))
			<div class="alert alert-success alert-block">
				<button type="button" class="close" data-dismiss="alert">×</button>	
			        <strong>{{ $message }}</strong>
			</div>
			@endif

            <!-- Default box -->
            <a href="{{ route('plan.create') }}" class="btn btn-primary">Agregar plan</a>
            <br><br>
            <div class="card card-primary">
              <div class="card-header">
                <h3 class="card-title">{{ __('Listado de Planes') }}</h3>

                <div class="card-tools">
                  <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
                    <i class="fas fa-minus"></i></button>
                  <button type="button" class="btn btn-tool" data-card-widget="remove" data-toggle="tooltip" title="Remove">
                    <i class="fas fa-times"></i></button>
                </div>
              </div>
              <div class="card-body">
                
	              <table id="example1" class="table table-bordered table-striped">
	                <thead>
	                <tr>
	                  <th>Titulo</th>
	                  <th>Precio</th>
	                  <th>Frecuencia de Cobro</th>
	                  <th>Cobros Recurrentes</th>
	                  <th>Estado</th>
	                  <th>Acciones</th>
	                </tr>
	                </thead>
	                <tbody>
	                @foreach ($plans as $plan)
	                <tr>
	                  <td>{{ $plan->titulo }}</td>
	                  <td>${{ number_format($plan->precio, 0) }}</td>
	                  <td>{{ $plan->frecuencia_cobro }} Mes (es).</td>
	                  <td>{{ $plan->recurrente==1 ? 'Si' : 'No' }}</td>
	                  <td>{{ $plan->status==1 ? 'Activo':'Oculto' }}</td>
	                  <td>
	                  	<div class="btn-group">
	                  		<a href="{{ route('plan.edit', ['plan' => $plan->id]) }}">
	                        	<button type="button" class="btn btn-default" title="Editar"><i class="nav-icon fas fa-edit"></i></button>
	                        </a>
	                        <a href="{{ route('plan.setStatus', ['plan' => $plan->id]) }}">
	                        	<button type="button" class="btn btn-default" title="{{ $plan->status==1 ? 'Ocultar':'Activar' }}"><i class="nav-icon fas fa-{{ $plan->status==1 ? 'ban':'check-circle' }}"></i></button>
	                        </a>
	                        <a href="{{ route('plan.destroy', ['plan' => $plan->id]) }}" onclick="return confirm('¿Estas seguro de querer eliminar este registro?. Se perderan todos los datos relacionados al mismo.')">
	                        	<button type="button" class="btn btn-default" title="Eliminar"><i class="nav-icon fas fa-trash-alt"></i></button>
	                        </a>
	                      </div>
	                  </td>
	                </tr>
	                @endforeach
	                </tbody>
	                <tfoot>
	                <tr>
	                  <th>Titulo</th>
	                  <th>Precio</th>
	                  <th>Frecuencia de Cobro</th>
	                  <th>Cobros Recurrentes</th>
	                  <th>Estado</th>
	                  <th>Acciones</th>
	                </tr>
	                </tfoot>
	            </table>


              </div>
              <!-- /.card-body -->
            </div>
            <!-- /.card -->
          </div>
        </div>
      </div>
    </section>
    <!-- /.content -->
@endsection

@section('extras-js')
    <!-- DataTables -->
    <script src="{{ asset('AdminLTE-3.0.2/AdminLTE-3.0.2/plugins/datatables/jquery.dataTables.js') }}"></script>
    <script src="{{ asset('AdminLTE-3.0.2/AdminLTE-3.0.2/plugins/datatables-bs4/js/dataTables.bootstrap4.js') }}"></script>

    <script>
	  $(function () {
	    $("#example1").DataTable();
	    $('#example2').DataTable({
	      "paging": true,
	      "lengthChange": false,
	      "searching": false,
	      "ordering": true,
	      "info": true,
	      "autoWidth": false,
	    });
	  });
	</script>
@endsection